import type { OrbConfig } from '../core/OrbConfig';
import { DEFAULT_ORB_CONFIG } from '../core/OrbConfig';

export const defaultPresets: OrbConfig[] = [
  {
    id: 'purple-energy',
    label: 'Purple Energy',
    baseRadius: 0.5,
    rotation: { xSpeed: 0.2, ySpeed: 0.1 },
    noise: { scale: 1.0, intensity: 0.5, speed: 0.2, detail: 0.5 },
    colors: { inner: '#ff00ff', outer: '#4b0082', accent: '#00ffff', background: '#000000', gradientBias: 0.5 },
    glow: { intensity: 0.6, threshold: 0.1, radius: 0.5 },
    details: { bandCount: 0, bandSharpness: 0.5, particleDensity: 0 },
    bloom: { enabled: true, strength: 1.0, radius: 0.4, threshold: 0.0 },
    post: { ...DEFAULT_ORB_CONFIG.post, chromaticAberration: true },
    animation: { loopSeconds: 10, easing: 'linear' },
    version: 1,
  },
  {
    id: 'blue-plasma',
    label: 'Blue Plasma',
    baseRadius: 0.6,
    rotation: { xSpeed: 0.3, ySpeed: 0.2 },
    noise: { scale: 1.5, intensity: 0.7, speed: 0.3, detail: 0.6 },
    colors: { inner: '#00ffff', outer: '#0000ff', accent: '#ffffff', background: '#000000', gradientBias: 0.6 },
    glow: { intensity: 0.8, threshold: 0.2, radius: 0.6 },
    details: { bandCount: 3, bandSharpness: 0.7, particleDensity: 0.2 },
    bloom: { enabled: true, strength: 1.5, radius: 0.6, threshold: 0.1 },
    post: { ...DEFAULT_ORB_CONFIG.post, filmGrain: { enabled: true, intensity: 0.1 } },
    animation: { loopSeconds: 5, easing: 'easeInOut' },
    version: 1,
  },
   {
    id: 'orange-ember',
    label: 'Orange Ember',
    baseRadius: 0.55,
    rotation: { xSpeed: 0.1, ySpeed: 0.05 },
    noise: { scale: 0.8, intensity: 0.6, speed: 0.1, detail: 0.4 },
    colors: { inner: '#ff4500', outer: '#8b0000', accent: '#ffff00', background: '#1a0500', gradientBias: 0.4 },
    glow: { intensity: 0.5, threshold: 0.0, radius: 0.4 },
    details: { bandCount: 0, bandSharpness: 0.0, particleDensity: 0.5 },
    bloom: { enabled: true, strength: 0.8, radius: 0.3, threshold: 0.2 },
    post: { ...DEFAULT_ORB_CONFIG.post, chromaticAberration: false },
    animation: { loopSeconds: 8, easing: 'bounce' },
    version: 1,
  },
  {
    id: 'neon-grid',
    label: 'Neon Grid',
    baseRadius: 0.45,
    rotation: { xSpeed: 0.05, ySpeed: 0.6 },
    noise: { scale: 0.6, intensity: 0.35, speed: 0.8, detail: 0.4 },
    colors: { inner: '#00f5ff', outer: '#0059ff', accent: '#ff00f5', background: '#050811', gradientBias: 0.55 },
    glow: { intensity: 0.7, threshold: 0.05, radius: 0.6 },
    details: { bandCount: 8, bandSharpness: 0.8, particleDensity: 0.25 },
    bloom: { enabled: true, strength: 1.7, radius: 0.55, threshold: 0.0 },
    post: { ...DEFAULT_ORB_CONFIG.post, chromaticAmount: 0.003, filmGrain: { enabled: true, intensity: 0.12 } },
    animation: { loopSeconds: 6, easing: 'elastic' },
    version: 1,
  },
  {
    id: 'deep-space',
    label: 'Deep Space',
    baseRadius: 0.6,
    rotation: { xSpeed: 0.08, ySpeed: 0.18 },
    noise: { scale: 1.4, intensity: 0.75, speed: 0.35, detail: 0.8 },
    colors: { inner: '#2cf1ff', outer: '#012c5f', accent: '#f7f1d5', background: '#02030b', gradientBias: 0.4 },
    glow: { intensity: 0.6, threshold: 0.15, radius: 0.65 },
    details: { bandCount: 12, bandSharpness: 0.7, particleDensity: 0.5 },
    bloom: { enabled: true, strength: 1.2, radius: 0.5, threshold: 0.05 },
    post: { ...DEFAULT_ORB_CONFIG.post, dof: { ...DEFAULT_ORB_CONFIG.post.dof, enabled: true, focus: 1.2, aperture: 0.0002, maxBlur: 0.01 } },
    animation: { loopSeconds: 12, easing: 'easeInOut' },
    version: 1,
  },
  {
    id: 'forest-glow',
    label: 'Forest Glow',
    baseRadius: 0.52,
    rotation: { xSpeed: 0.12, ySpeed: -0.12 },
    noise: { scale: 0.9, intensity: 0.45, speed: 0.15, detail: 0.45 },
    colors: { inner: '#6cff9f', outer: '#0f3b2e', accent: '#c4ff7f', background: '#04130e', gradientBias: 0.35 },
    glow: { intensity: 0.5, threshold: 0.05, radius: 0.45 },
    details: { bandCount: 4, bandSharpness: 0.45, particleDensity: 0.3 },
    bloom: { enabled: true, strength: 0.9, radius: 0.35, threshold: 0.15 },
    post: { ...DEFAULT_ORB_CONFIG.post, chromaticAberration: false, filmGrain: { enabled: false, intensity: 0.05 } },
    animation: { loopSeconds: 14, easing: 'linear' },
    version: 1,
  },
  {
    id: 'sunrise-shell',
    label: 'Sunrise Shell',
    baseRadius: 0.58,
    rotation: { xSpeed: -0.05, ySpeed: 0.22 },
    noise: { scale: 1.1, intensity: 0.55, speed: 0.25, detail: 0.55 },
    colors: { inner: '#ffb88c', outer: '#ff5f6d', accent: '#ffe6a7', background: '#120505', gradientBias: 0.42 },
    glow: { intensity: 0.7, threshold: 0.08, radius: 0.55 },
    details: { bandCount: 6, bandSharpness: 0.55, particleDensity: 0.2 },
    bloom: { enabled: true, strength: 1.3, radius: 0.45, threshold: 0.05 },
    post: { ...DEFAULT_ORB_CONFIG.post, chromaticAmount: 0.0025, filmGrain: { enabled: true, intensity: 0.07 } },
    animation: { loopSeconds: 9, easing: 'easeInOut' },
    version: 1,
  },
  {
    id: 'mono-minimal',
    label: 'Mono Minimal',
    baseRadius: 0.5,
    rotation: { xSpeed: 0.0, ySpeed: 0.15 },
    noise: { scale: 0.7, intensity: 0.25, speed: 0.05, detail: 0.2 },
    colors: { inner: '#f5f5f5', outer: '#b3b3b3', accent: '#ffffff', background: '#0b0b0b', gradientBias: 0.5 },
    glow: { intensity: 0.35, threshold: 0.2, radius: 0.35 },
    details: { bandCount: 0, bandSharpness: 0.0, particleDensity: 0.0 },
    bloom: { enabled: false, strength: 0.5, radius: 0.2, threshold: 0.3 },
    post: { ...DEFAULT_ORB_CONFIG.post, chromaticAberration: false, filmGrain: { enabled: true, intensity: 0.05 } },
    animation: { loopSeconds: 20, easing: 'linear' },
    version: 1,
  },
];
